services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_PATH=/app/data/habits.db
    volumes:
      - server_data:/app/data
    networks:
      - habit-tracker-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/habits"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - API_URL=http://server:8080
    depends_on:
      server:
        condition: service_healthy
    networks:
      - habit-tracker-network

volumes:
  server_data:
    driver: local

networks:
  habit-tracker-network:
    driver: bridge 